f = open("demofile2.txt", "a")
f.write("Datta Meghe College of Engineering")
f.close()
f = open("demofile2.txt", "r")
print(f.read())
f = open("demofile2.txt", "a")
f.write("Datta Meghe College of Engineering")
f.close()
f = open("demofile2.txt", "r")
print(f.read())